---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - awscli
    - cask
    - coreutils
    - curl
    - fasd
    - findutils
    - fortune
    - git
    - httpie
    - hugo
    - imagemagick
    - nmap
    - python
    - python3
    - readline
    - rename
    - ssh-copy-id
    - terraform
    - tree
    - vim
    - watch
    - wget
    - zsh

- name: Tap into the Homebrew Cask Beta apps
  homebrew_tap: tap=caskroom/versions state=present

- name: Install libraries with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - appcleaner
    - atom
    - bartender
    - clipmenu
    - daisydisk
    - debookee
    - flux
    - google-chrome
    - google-drive
    - istat-menus
    - iterm2
    - keka
    - little-snitch
    - quip
    - sketch
    - transmit
    - tunnelblick

- name: Cleanup Brew packages
  command: brew cleanup

- name: Cleanup Brew Cask packages
  command: brew cask cleanup

- name: Setup updatebrew.sh
  get_url: url=https://gitlab.com/snippets/7240/raw dest=~/.bin/updatebrew.sh mode=0755
